In [ ]:
# FILTERING

In [3]:
import pandas as pd
groceries = pd.read_pickle('groceries_with_new_columns.pkl')
groceries.head()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday

In [4]:
# filtering Low Inventory column with only Low Inventory tag
groceries.loc[groceries['Low Inventory'] == 'Low Inventory']

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [6]:
# filtering Low Inventory column with only Low Inventory tag (only one column so without loc possible but if 2 columns , there must be  .loc to use)
groceries[groceries['Low Inventory'] == 'Low Inventory']

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.7,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [7]:
# filtering Low Inventory column with only Low Inventory tag and price of those and Inventory column of those as well
groceries.loc[groceries['Low Inventory'] == 'Low Inventory', ['Price_Dollars', 'Inventory']]

    Price_Dollars  Inventory
15           4.49         32
17           1.50         27
20           2.99          5

In [22]:
# before filtering, remove if there is any space and save it to Data Frame. after saving, it will be reflected following steps
groceries.Subcategory = groceries.Subcategory.str.strip()
groceries.Subcategory[17] # there is no space before Snacks

'Snacks'

In [20]:
# filtering Subcategory column with only Snacks tag (there was space before snacks)
groceries.loc[groceries['Subcategory'] == 'Snacks']

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.5,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.0,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [23]:
# filtering 2 columns Low Inventory with Low Inventory tag only and Subcategory with Snacks tag only
mask = (groceries['Low Inventory'] == 'Low Inventory') & (groceries['Subcategory'] == 'Snacks')

In [24]:
groceries[mask]

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.6,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [25]:
# filtering only 'Subcategory', 'Item', 'Inventory' columns with 'Low Inventory' and 'Snacks' tags only
groceries.loc[mask, ['Subcategory', 'Item', 'Inventory']]

   Subcategory                   Item  Inventory
17      Snacks  Apple Sauce - organic         27
20      Snacks                Raisins          5